<?php

/**
 * @file
 * Primary module hooks for fn_notes module.
 */

use Drupal\Core\Site\Settings;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\Core\Form\FormStateInterface;


/* NOEUD */
function fn_notes_preprocess_node__note__teaser(&$variables) {
  // Récupération de l'url de l'image du Championnat.
  $element = $variables['elements'];
  $fieldChampionnat = $element['field_championnat'];
  $termChampionnat = $fieldChampionnat['#items']->referencedEntities()[0];
  $mediaChampionnat = $termChampionnat->get('field_logo')->referencedEntities()[0];
  $fileUrlChampionnat = $mediaChampionnat->field_media_image->referencedEntities()[0]->getFileUri();
  $variables['img_championnat'] = file_create_url($fileUrlChampionnat);

  $fieldEquipeAdomicile = $element['field_equipe_a_domicile'];
  $termEquipeAdomicile = $fieldEquipeAdomicile['#items']->referencedEntities()[0];
  $mediaEquipeAdomicile = $termEquipeAdomicile->get('field_logo')->referencedEntities()[0];
  $fileUrlEquipeAdomicile = $mediaEquipeAdomicile->field_media_image->referencedEntities()[0]->getFileUri();
  $variables['img_equipe_a_domicile'] = file_create_url($fileUrlEquipeAdomicile);

  $fieldEquipeAExterieur = $element['field_equipe_a_exterieur'];
  $termEquipeAExterieur = $fieldEquipeAExterieur['#items']->referencedEntities()[0];
  $mediaEquipeAExterieur = $termEquipeAExterieur->get('field_logo')->referencedEntities()[0];
  $fileUrlEquipeAExterieur = $mediaEquipeAExterieur->field_media_image->referencedEntities()[0]->getFileUri();
  $variables['img_equipe_a_exterieur'] = file_create_url($fileUrlEquipeAExterieur);
}

function fn_notes_preprocess_node__note__full(&$variables) {
  $element = $variables['elements'];
  $saison = explode('/', $element['field_saison'][0]['#plain_text'])[0];

  $fieldEquipeAdomicile = $element['field_equipe_a_domicile'];
  $termEquipeAdomicile = $fieldEquipeAdomicile['#items']->referencedEntities()[0];
  $mediaEquipeAdomicile = $termEquipeAdomicile->get('field_logo')->referencedEntities()[0];
  $fileUrlEquipeAdomicile = $mediaEquipeAdomicile->field_media_image->referencedEntities()[0]->getFileUri();
  $variables['img_equipe_a_domicile'] = file_create_url($fileUrlEquipeAdomicile);

  $fieldEquipeAExterieur = $element['field_equipe_a_exterieur'];
  $termEquipeAExterieur = $fieldEquipeAExterieur['#items']->referencedEntities()[0];
  $mediaEquipeAExterieur = $termEquipeAExterieur->get('field_logo')->referencedEntities()[0];
  $fileUrlEquipeAExterieur = $mediaEquipeAExterieur->field_media_image->referencedEntities()[0]->getFileUri();
  $variables['img_equipe_a_exterieur'] = file_create_url($fileUrlEquipeAExterieur);

  // Import data Match.
  $idMatch = $element['#node']->get('field_id_match')->getString() ?? NULL;
  if ($idMatch) {
    $dataMatch = getMatch($idMatch);

    // Tableau statistique match de football.
    $equipeHomeJoueurs = $dataMatch['Home']['players'];
    $equipeAwayJoueurs = $dataMatch['Away']['players'];

    $topTouchesBalles = [];
    $topTouchesBallesHome = [];
    $topTouchesBallesAway= [];

    // Itération sur les joueurs home.
    foreach ($equipeHomeJoueurs as $joueur) {
      $data = [
        'joueur' => $joueur['info']['lastname'] ?? '',
        'touches' => $joueur['stat']['touches'] ?? 0,
      ];
      $topTouchesBallesHome[] = $data;
      $topTouchesBalles[] = $data;
    }
    // Itération sur les joueurs away.
    foreach ($equipeAwayJoueurs as $joueur) {
      $data = [
        'joueur' => $joueur['info']['lastname'] ?? '',
        'touches' => $joueur['stat']['touches'] ?? 0,
      ];
      $topTouchesBallesAway[] = $data;
      $topTouchesBalles[] = $data;
    }

    // Une fois les tableaux construits, on les tries.
    usort($topTouchesBallesHome, function ($item1, $item2) {
      return $item2['touches'] <=> $item1['touches'];
    });
    usort($topTouchesBallesAway, function ($item1, $item2) {
      return $item2['touches'] <=> $item1['touches'];
    });
    usort($topTouchesBalles, function ($item1, $item2) {
      return $item2['touches'] <=> $item1['touches'];
    });

    // On construit les tableaux nécessaires pour les graphiques Highcharts.
    $variables['#attached']['drupalSettings']['note']['touchesTotal'] = buildHighchartsJS(
      array_slice($topTouchesBalles, 0, 5), sprintf('%s + %s', $dataMatch['Home']['club'], $dataMatch['Away']['club'])
    );
    $variables['#attached']['drupalSettings']['note']['touchesTotalHome'] = buildHighchartsJS(
      array_slice($topTouchesBallesHome, 0, 5), $dataMatch['Home']['club']
    );
    $variables['#attached']['drupalSettings']['note']['touchesTotalAway'] = buildHighchartsJS(
      array_slice($topTouchesBallesAway, 0, 5), $dataMatch['Away']['club']
    );


    // Récupération de l'url du maillot domicile.
    $termNameEquipeADomicile = $termEquipeAdomicile->getName();
    $urlMaillotDomicile = sprintf('maillots/%s/%s_1.png', $saison, str_replace(' ', '_', strtolower(stripAccents($termNameEquipeADomicile))));
    if (file_exists(sprintf('public://%s', $urlMaillotDomicile))) {
      $variables['maillotDomicile'] = sprintf('/sites/default/files/%s', $urlMaillotDomicile);
    } else {
      $variables['maillotDomicile'] = '/themes/custom/footballnotes/img/t-shirt-white.png';
    }
    // Récupération de l'url du maillot extérieur.
    $termNameEquipeAExterieur = $termEquipeAExterieur->getName();
    $urlMaillotExterieur = sprintf('maillots/%s/%s_2.png', $saison, str_replace(' ', '_', strtolower(stripAccents($termNameEquipeAExterieur))));
    if (file_exists(sprintf('public://%s', $urlMaillotExterieur))) {
      $variables['maillotExterieur'] = sprintf('/sites/default/files/%s', $urlMaillotExterieur);
    } else {
      $variables['maillotExterieur'] = '/themes/custom/footballnotes/img/t-shirt-black.png';
    }

    $variables['data']['equipeHome'] = buildEquipeMatch($dataMatch['Home']);
    $variables['data']['equipeAway'] = buildEquipeMatch($dataMatch['Away']);
  }
}

/* FORMULAIRE */
function fn_notes_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // On choisit le formulaire exposé de notre vue.
  if ($form['#id'] === 'views-exposed-form-note-hub') {

    // On récupère les inputs du formulaire.
    $inputs = $form_state->getUserInput();

    // On créer la requête qui va nous permettre de récupérer
    // les ID des paragraphes respectants les conditions du formulaire.
    $queryParagraphs = \Drupal::entityQuery('paragraph')
      ->condition('type', 'saison_championnat');

    // Ajout condition SAISON.
    if ($inputs['saison'] !== 'All') {
      $queryParagraphs->condition('field_saison', $inputs['saison']);
    }

    // Ajout condition CHAMPIONNAT.
    if ($inputs['championnat'] !== 'All') {
      $queryParagraphs->condition('field_championnat', $inputs['championnat']);
    }

    // On récupère les résultats des paragraphes.
    $resultatParagraphs = $queryParagraphs->execute();

    // On va maintenant récupèrer les équipes associées à ces paragraphes;
    // Donc celles qui respectent les conditions du formulaire.
    $equipesDuChampionnatSelectionne = Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'equipe')
      ->condition('field_saisons_championnats', $resultatParagraphs, 'IN')
      ->execute();

    // On itère sur les options du select "Equipe".
    foreach ($form['equipe']['#options'] as $key => $nomEquipe) {
      if ($key !== 'All') {
        // Si l'équipe ne fait pas partie du championnat sélectionné
        // alors on la retire du select.
        if (!in_array($key, $equipesDuChampionnatSelectionne)) {
          unset($form['equipe']['#options'][$key]);
        }
      }
    }
  }
}

function fn_notes_preprocess_views_exposed_form(&$variables) {
  if ($variables['form']['#id'] === 'views-exposed-form-note-hub') {
    $variables['form']['saison']['#attributes'] = addSelectPicker($variables['form']['saison']['#attributes']);
    $variables['form']['championnat']['#attributes'] = addSelectPicker($variables['form']['saison']['#attributes']);
    $variables['form']['equipe']['#attributes'] = addSelectPicker($variables['form']['saison']['#attributes']);
  }
}

function addSelectPicker($formField) {
  $formField['class'][] = 'selectpicker';
  $formField['data-live-search'] = "TRUE";

  return $formField;
}

/**
 * Fonction pour récupérer un match.
 *
 * @param $matchID
 */
function getMatch($matchID) {
  $mpgURL = Settings::get('mpg-url');
  $url = sprintf('%s/championship/match/%s', $mpgURL, $matchID);

  $client = \Drupal::httpClient();
  $request = $client->get($url);
  $resultat = $request->getBody()->getContents();
  $decodeResultat = json_decode($resultat, TRUE);
  return $decodeResultat;
}

function buildHighchartsJS($arrayData, $serieName) {
  $result = [];
  foreach (array_slice($arrayData, 0, 5) as $key => $value) {
    $result['categorie'][] = $value['joueur'];
    $result['serie'][] = $value['touches'];
    $result['serieName'] = $serieName;
  }
  return $result;
}

// Fonction permettant la création des équipes Home/Away.
function buildEquipeMatch($data) {
  $result = [];
  foreach ($data['players'] as $player) {
    if ($player['info']['sub'] === 1) {
      $type = 'remplacants';
    } else {
      switch ($player['info']['position']) {
        case 'Goalkeeper';
          $type = 'gardien';
          break;
        case 'Defender';
          $type = 'defenseurs';
          break;
        case 'Midfielder';
          $type = 'milieux';
          break;
        case 'Forward';
        case 'Striker';
          $type = 'attaquants';
          break;
        default:
          $type = 'remplacants';
          break;
      }
    }

    switch ($type) {
      case 'gardien':
        $result[$type][] = [
          'id' => $player['info']['idplayer'],
          'name' => $player['info']['lastname'],
          'position' => $player['info']['formation_place'],
          'stats' => [
            'globales' => [
              'Arrêts tirs cadrés' => isset($player['stat']['saved_ibox']) ? $player['stat']['saved_ibox'] : NULL,
              'Arrêts tirs non cadrés' => isset($player['stat']['saved_obox']) ? $player['stat']['saved_obox'] : NULL,
              'Arrêts plongeons' => isset($player['stat']['diving_save']) ? $player['stat']['diving_save'] : NULL,
              'Pénalty sauvé' => isset($player['stat']['penalty_save']) ? $player['stat']['penalty_save'] : NULL,
              'Carton jaune' => isset($player['stat']['yellow']) ? $player['stat']['yellow'] : NULL,
              'Carton rouge' => isset($player['stat']['red_card']) ? $player['stat']['red_card'] : NULL,
              'Erreurs menant à un tir' => isset($player['stat']['error_lead_to_shot']) ? $player['stat']['error_lead_to_shot'] : NULL,
              'Erreurs menant à un but' => isset($player['stat']['error_lead_to_goal']) ? $player['stat']['error_lead_to_goal'] : NULL,
            ],
          ]
        ];
        break;
      case 'defenseurs':
      case 'milieux':
      case 'attaquants':
      case 'remplacants':
      default:
        $result[$type][] = [
          'id' => $player['info']['idplayer'],
          'name' => $player['info']['lastname'],
          'position' => $player['info']['formation_place'],
          'stats' => [
            'globales' => [
              'Touches' => isset($player['stat']['touches']) ? $player['stat']['touches'] : NULL,
              '% de passes réussies' => isset($player['stat']['pass']) ? sprintf('%s %%', round($player['stat']['pass']*100, 1)) : NULL,
              'Duels gagnés' => isset($player['stat']['duel_won']) ? $player['stat']['duel_won'] : NULL,
              'Duels perdus' => isset($player['stat']['duel_lost']) ? $player['stat']['duel_lost'] : NULL,
              'Dépossédé du ballon' => isset($player['stat']['dispossessed']) ? $player['stat']['dispossessed'] : NULL,
              'Touches ratées' => isset($player['stat']['unsuccessful_touch']) ? $player['stat']['unsuccessful_touch'] : NULL,
              'Fautes' => isset($player['stat']['fouls']) ? $player['stat']['fouls'] : NULL,
              'Fautes subies' => isset($player['stat']['was_fouled']) ? $player['stat']['was_fouled'] : NULL,
              'Gestes dangereux' => isset($player['stat']['dangerous_play']) ? $player['stat']['dangerous_play'] : NULL,
            ],
            'defensives' => [
              'Hors-jeu provoqués' => isset($player['stat']['offside_provoked']) ? $player['stat']['offside_provoked'] : NULL,
              'Interceptions' => isset($player['stat']['interception']) ? $player['stat']['interception'] : NULL,
              'Tacles gagnés' => isset($player['stat']['won_tackle']) ? $player['stat']['won_tackle'] : NULL,
              'Tacle en tant que dernier défenseur' => isset($player['stat']['last_man_tackle']) ? $player['stat']['last_man_tackle'] : NULL,
              'Tacles ratés' => isset($player['stat']['bad_tackle']) ? $player['stat']['bad_tackle'] : NULL,
              'CSC' => isset($player['stat']['own_goals']) ? $player['stat']['own_goals'] : NULL,
              'Erreur menant à un tir' => isset($player['stat']['error_lead_to_shot']) ? $player['stat']['error_lead_to_shot'] : NULL,
              'Erreur menant à un but' => isset($player['stat']['error_lead_to_goal']) ? $player['stat']['error_lead_to_goal'] : NULL,
              'Centres bloqués' => isset($player['stat']['last_man_tackle']) ? $player['stat']['last_man_tackle'] : NULL,
            ],
            'offensives' => [
              'Buts' => isset($player['stat']['goals']) ? $player['stat']['goals'] : NULL,
              'Passe décisive' => isset($player['stat']['goal_assist']) ? $player['stat']['goal_assist'] : NULL,
              'Occasions dangereuses créées' => isset($player['stat']['big_chance_created']) ? $player['stat']['big_chance_created'] : NULL,
              'Occasions dangereuses ratées' => isset($player['stat']['big_chance_missed']) ? $player['stat']['big_chance_missed'] : NULL,
              'Penaltys gagnés' => isset($player['stat']['penalty_won']) ? $player['stat']['penalty_won'] : NULL,
              'Penaltys concédés' => isset($player['stat']['penalty_conceded']) ? $player['stat']['penalty_conceded'] : NULL,
              'Tentatives de tirs' => isset($player['stat']['total_scoring_att']) ? $player['stat']['total_scoring_att'] : NULL,
              'Tirs cadrés' => isset($player['stat']['total_scoring_att']) ? $player['stat']['total_scoring_att'] - $player['stat']['shot_off_target'] : NULL,
              'Tirs non cadrés' => isset($player['stat']['shot_off_target']) ? $player['stat']['shot_off_target'] : NULL,
              'Hors-jeu' => isset($player['stat']['total_offside']) ? $player['stat']['total_offside'] : NULL,
              'Corners gagnés' => isset($player['stat']['won_corners']) ? $player['stat']['won_corners'] : NULL,
            ],
          ]
        ];
        break;
    }
  }

  return $result;
}

function stripAccents($str) {
  return strtr(utf8_decode($str), utf8_decode('àáâãäçèéêëìíîïñòóôõöùúûüýÿÀÁÂÃÄÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝ'), 'aaaaaceeeeiiiinooooouuuuyyAAAAACEEEEIIIINOOOOOUUUUY');
}
